version: '3'

services:
  ledfx:
    image: ledfx
    container_name: LedFX
    network_mode: host
    volumes:
      - ./config:/home/ledfx/.ledfx
      - /var/run/user/1000/pulse:/home/ledfx/audio
    environment:
      - PULSE_SERVER=unix:/home/ledfx/audio/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    build:
      context: .
      args:
        VERSION: master
    restart: unless-stopped