### Create docker image from venv-image as compile-image to speed up builds
#
FROM ledfx-venv AS compile-image
ENV PATH="/ledfx/venv/bin:$PATH"
WORKDIR /ledfx
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc=4:8.3.0-1 \
        libc-dev && apt-get clean -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir ledfx==0.10.4
