name: self-hosted

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        uses: docker/setup-buildx-action@v1
        id: builder2
      -
        name: Builder 1 name
        run: echo ${{ steps.builder1.outputs.name }}
      -
        name: Builder 2 name
        run: echo ${{ steps.builder2.outputs.name }}
      -
        name: Builder 2 name
        run: echo ${{ steps.builder2.outputs.name }}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: spirocekano/ledfx:latest,spirocekano/ledfx:0.10.4
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: VERSION=dev
          push: true
          tags: spirocekano/ledfx:dev
          cache-from: type=local,src=/tmp/.buildx-dev-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-dev-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


